apiVersion: v1
kind: Service
metadata:
  name: node-hostname
spec:
  selector:
    app: node-hostname
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000